LANGUAGES = {
    'en': {
        'app_name': 'MVNO API Platform',
        'supplier_api': 'Supplier API',
        'quadcell': 'Quadcell',
        'montnet': 'MontNet', 
        'simlessly': 'Simlessly',
        'worldmove': 'WorldMove',
        'welcome_message': 'Welcome to MVNO API Integration Platform',
        'platform_description': 'This platform integrates API interfaces from multiple SIM card suppliers, providing a unified interface for operations.',
        'supported_suppliers': 'Supported Suppliers:',
        'sim_management': 'Provides SIM card configuration and management services',
        'single_request': 'Single Request',
        'batch_processing': 'Batch Processing',
        'company_management': 'Company Management',
        'select_endpoint': 'Select Endpoint',
        'enpoint_info': 'Endpoint Info.',
        'send_request': 'Send Request',
        'response_result': 'Response Result',
        'select_Excel_File': 'Select Excel File',
        'upload_excel': 'Upload Excel File',
        'select_company': 'Select Company',
        'request_interval': 'Request Interval (seconds)',
        'request_interval_note': 'Setting it to 0 means no interval, leaving it blank defaults to 0',
        'start_processing': 'Start Processing',
        'processing': 'Processing',
        'add_new_company': 'Add New Company',
        'company_name': 'Company Name',
        'auth_key': 'AuthKey',
        'add': 'Add',
        'actions': 'Actions',
        'edit': 'Edit',
        'delete': 'Delete',
        'no_data': 'No data available',
        'copyright': 'Quadcell MVNO API Integration Platform',
        'select_language': 'Select Language',
        
        # Common texts
        'please_select': 'Please select',
        'loading': 'Loading...',
        'success': 'Success',
        'error': 'Error',
        'download': 'Download',
        'refresh': 'Refresh',
        'stop': 'Stop',
        'start': 'Start',
        'api_Operations': 'API Operations',
        'api_endpoint': 'API Endpoint',
        'imsi_number_or_range': "IMSI number or range",
        'other_required_parameters': "Other required parameters",
        'download_template': 'Download Excel Template',
        'template_note': 'Download template file, fill in data according to format and then upload',
        'enter_parameter_value': "Enter value for",        
        'no_description_available': "No description available",
        'request_interval_non_negative': "Request interval must be non-negative",
        'processing_failed': "Processing failed",
        'unknown_error': "Unknown error",        
        'added_succeed': "Added Succeed",
        'added_failed': "Added Failed",
        'updated_succeed': "Updated Succeed",
        'updated_failed': "Updated Failed",
        'deleted_succeed': "Deleted Succeed",
        'deleted_failed': "Deleted Failed",                                

        # Form labels and buttons
        'single_title': 'Single Request Instructions',
        'batch_title': 'Batch Processing Instructions',
        'choose_file': 'Choose File',
        'no_file_selected': 'No file selected',
        'excel_files_only': 'Excel files only (.xlsx, .xls)',
        'set_to_zero': 'Set to 0 for no delay, leave blank defaults to 0',
        'click_to_download': 'Click to download',
        'process_completed': 'Processing completed',
        'result_file_generated': 'Result file has been generated, ',
        'processing_please_wait': 'Processing, please wait...',
        'request_processing': 'Request processing, please wait...',
        'debug_mode': 'Debug Mode',
        'debug_mode_description': 'Enable to show detailed API request information for troubleshooting',
        'debug_information': 'Debug Information',
        'api_url': 'API URL',
        'request_json': 'Request JSON',
        'encrypted_request': 'Encrypted Request',
        'response_raw': 'Raw Response',
        'timestamp': 'Timestamp',
        'formatted_response': 'Formatted Response',

        # MontNet specific
        'montnet_single_description': 'Select API endpoints and fill in parameters, the system will send single requests and return results.',
        'montnet_single_note': 'Note: Fixed parameters (authKey) are automatically included, no need to add manually.',
        'montnet_iccid_note': 'ICCID Note: MontNet API requires 20-digit ICCID (including check digit). If you have 19-digit ICCID, you can use the "Calculate Check Digit" button to automatically calculate the check digit.',
        'montnet_batch_description': 'Please upload Excel file, the file format should include the following columns:',
        'montnet_batch_columns': 'endpoint: API endpoint path, iccid: ICCID number or range (e.g., 8985211116317800000-8985211116317800999), other required parameter columns',
        'montnet_batch_note': 'The system will automatically expand ICCID ranges and send separate requests for each ICCID.',
        'montnet_calculate_check_digit': 'Calculate Check Digit',
        'montnet_endpoint_heartbeat': "Check if VMS API service is normal",
        'montnet_endpoint_qrysub': "Query user (SIM card) basic information",
        'montnet_endpoint_qrypacklist': "Query list of packages subscribed by user",
        'montnet_endpoint_queryQosQuota': "Query usage of packages subscribed by user",
        'montnet_endpoint_addpack': "Subscribe to package",
        'montnet_endpoint_delpack': "Delete package",
        'montnet_endpoint_quota_topup': "Top up package usage (only for 'Suspend' packages)",
        'montnet_endpoint_suspend': "Suspend package data service (only for Vendor = CMHK)",
        'montnet_endpoint_recover': "Resume package data service",
        'montnet_iccid_must_be_19_digits': "ICCID must be 19 digits",
        'montnet_iccid_19_digits_note': "19-digit ICCID (without check digit), must use calculate function to add check digit",
        'montnet_iccid_20_digits_note': "20-digit ICCID (with check digit), format is correct",
        'montnet_iccid_19_or_20_digits': "ICCID must be 19 digits (without check digit) or 20 digits (with check digit)",
        'montnet_enter_valid_19_digits': "Please enter a valid 19-digit ICCID (without check digit)",
        'montnet_check_digit_calculated': "Check digit calculated and added",
        'montnet_iccid_already_20_digits': "ICCID is already 20 digits (with check digit), no need to recalculate",
        'montnet_no_extra_params': "This endpoint requires no additional parameters (fixed parameters have been automatically added).",
        'montnet_get_params_failed': "Failed to get endpoint parameters",
        'montnet_enter_iccid_placeholder': "Please enter 19 or 20 digit ICCID",
        
        # Dynamic Config
        'montnet_endpoint_heartbeat': "Check if VMS API service is normal",
        'montnet_endpoint_qrysub': "Query user (SIM card) basic information",
        'montnet_endpoint_qrypacklist': "Query list of packages subscribed by user",
        'montnet_endpoint_queryQosQuota': "Query usage of packages subscribed by user",
        'montnet_endpoint_addpack': "Subscribe to package",
        'montnet_endpoint_delpack': "Delete package",
        'montnet_endpoint_quota_topup': "Top up package usage (only for 'Suspend' packages)",
        'montnet_endpoint_suspend': "Suspend package data service (only for Vendor = CMHK)",
        'montnet_endpoint_recover': "Resume package data service",
        'montnet_endpoint_qryLocation': "Query the current location information",        
        'montnet_param_authKey': 'Authentication key (automatically included)',
        'montnet_param_imsi': 'IMSI number (choose one with iccid/msisdn)',
        'montnet_param_iccid': 'ICCID number (choose one with imsi/msisdn)',
        'montnet_param_msisdn': 'MSISDN number (choose one with imsi/iccid)',
        'montnet_param_productId': 'Subscribed package ID',
        'montnet_param_subscriptionId': 'Subscribed package subscription ID',
        'montnet_param_packCode': 'Additional package code',
        'montnet_param_quota': 'Usage to top up (MB)',        
        
        
        # Quadcell specific
        'quadcell_single_description': 'Select API endpoints and fill in parameters, the system will send single requests and return results.',
        'quadcell_single_note': 'Note: The authKey parameter defaults to "SYtest21", but you can modify it manually.',
        'quadcell_company_select': 'Selecting a company will automatically fill the authKey, you can also modify it manually',
        'quadcell_batch_description': 'Please upload Excel file, the file format should include the following columns:',
        'quadcell_batch_columns': 'endpoint: API endpoint path, imsi: IMSI number or range (e.g., 454070041610000-454070041610999) - also applies to ICCID/MSISDN, other required parameter columns',
        'quadcell_batch_note': 'The system will automatically expand IMSI/ICCID/MSISDN ranges and send separate requests for each SIM.',
        'quadcell_company_manager': 'Company Manager',        
        'quadcell_company_mapping': 'Company Mapping Management',
        'quadcell_company_description': 'Here you can add, edit and delete company name and authKey mappings.',
        'quadcell_company_usage': 'In single requests and batch processing, you can select company names to automatically fill authKey.',
        'quadcell_company_authkey_priority': 'Selecting a company will use that company\'s authKey, with higher priority than authKey in Excel',
        'quadcell_company_select': 'Please Select Company',         
        'quadcell_fillin_company': 'Please fill-in Company Name and AuthKey',
        'quadcell_input_new_authkey': 'Please input new AuthKey for ', 
        'quadcell_blank_authkey_note': 'AuthKey cannot be blank',
        'quadcell_delete_company_note': 'Please be confirmed to delete company -',                     
        
        # Dynamic Config
        'quadcell_endpoint_qrysub': "Query user basic information",
        'quadcell_endpoint_qryusage': "Query user data usage",
        'quadcell_endpoint_qrypacklist': "Query list of packages subscribed by user",
        'quadcell_endpoint_qrypackquota': "Query usage of packages subscribed by user",
        'quadcell_endpoint_qryquota': "Query FUP package usage",
        'quadcell_endpoint_addsub': "Create user subscription",
        'quadcell_endpoint_delsub': "Delete user subscription",
        'quadcell_endpoint_suspend': "Suspend user service",
        'quadcell_endpoint_recover': "Recover user service",
        'quadcell_endpoint_extend': "Extend user service validity",
        'quadcell_endpoint_addpack': "Add service package",
        'quadcell_endpoint_delpack': "Delete service package",
        'quadcell_endpoint_rechargepackquota': "Recharge package usage",
        'quadcell_endpoint_resetquota': "Reset FUP data usage",
        'quadcell_endpoint_clearquota': "Clear FUP remaining usage",
        'quadcell_endpoint_rechargequota': "Recharge FUP remaining usage",
        'quadcell_endpoint_addFupCode': "Add FUP rule for data package (only for 45400/45431)",
        'quadcell_endpoint_delFupCode': "Delete FUP rule for data package (only for 45400/45431)",
        'quadcell_endpoint_cancelLoc': "Force user to detach from network",
        'quadcell_endpoint_submitsms': "Send SMS to user",
        'quadcell_endpoint_qrystatus': "Query eSIM status",
        'quadcell_endpoint_esim_order': "Order eSIM and add package",
        'quadcell_endpoint_esim_qryaccount': "Query eSIM pool of user account",
        'quadcell_endpoint_qryorderhistory': "Query package order history",
        'quadcell_param_imsi': 'IMSI number (choose one with iccid/msisdn)',
        'quadcell_param_iccid': 'ICCID number (choose one with imsi/msisdn)',
        'quadcell_param_msisdn': 'MSISDN number (choose one with imsi/iccid)',
        'quadcell_param_beginDate': 'Start date (yyyymmdd)',
        'quadcell_param_endDate': 'End date (yyyymmdd)',
        'quadcell_param_packCode': 'Package code',
        'quadcell_param_planCode': 'Service package code',
        'quadcell_param_validity': 'Validity period (days)',
        'quadcell_param_lastActiveTime': 'Last activation time (yyyymm)',
        'quadcell_param_initBalance': 'Initial balance',
        'quadcell_param_serviceId': 'Service ID (default 00 means all services)',
        'quadcell_param_append': 'Extension method: 0=reset, 1=append',
        'quadcell_param_noOfDays': 'Extension days (1-99999)',
        'quadcell_param_activeType': 'Activation type: 0=by date, 1=by country',
        'quadcell_param_activeDate': 'Activation date (yyyymmdd)',
        'quadcell_param_expTime': 'Deletion time (yyyymmddhhmmss)',
        'quadcell_param_packOrderSn': 'Package order serial number',
        'quadcell_param_rechargeQuota': 'Recharge usage (MB/minutes/pieces)',
        'quadcell_param_rechargeValue': 'Recharge data volume (MB)',
        'quadcell_param_fupCode': 'FUP rule code',
        'quadcell_param_smsMt': 'Recipient MSISDN',
        'quadcell_param_smsMo': 'Sender MSISDN (assigned by Quadcell)',
        'quadcell_param_smsText': 'SMS content',
        'quadcell_param_account': 'Customer account name',
        'quadcell_param_imsiType': 'Supports 45407/45400/45412',
        'quadcell_param_page': 'Page number (default first page)',
        'quadcell_param_pageSize': 'Page size (default 20 pages)',   
                
        
        # Simlessly specific
        'simlessly_single_description': 'Select API endpoints and fill in parameters, the system will send single requests and return results.',
        'simlessly_batch_description': 'Please upload Excel file, the file format should include the following columns:',
        'simlessly_batch_columns': 'endpoint: API endpoint path, iccid: ICCID number or range (e.g., 8985211116317800000-8985211116317800999), other required parameter columns',
        'simlessly_batch_note': 'The system will automatically expand ICCID ranges and send separate requests for each ICCID.',
        'simlessly_dot_notation': 'Note: Use dot notation to create nested structures (e.g., \'pageParam.pageNum\')',
        'simlessly_no_extra_params': 'This endpoint requires no additional parameters.',
        'simlessly_get_params_failed': 'Failed to get endpoint parameters',
        'simlessly_list_param_note': ' (use JSON array format, e.g.: ["45400", "45407"])',
        'simlessly_list_param_example': 'e.g.: ["45400", "45407"]',
        
        # Dynamic Config
        'simlessly_endpoint_profile_detail': "Query eSIM Details",
        'simlessly_endpoint_profile_log': "Query eSIM history records", 
        'simlessly_endpoint_profile_delete': "Delete eSIM configuration",
        'simlessly_endpoint_profile_updateParam': "Update eSIM configuration",        
        'simlessly_endpoint_ac_generate': "Generate eSIM",
        'simlessly_param_iccid': 'ICCID number',
        'simlessly_param_pageParam_pageNum': 'Page number',
        'simlessly_param_pageParam_pageSize': 'Page size',
        'simlessly_param_imsi': 'IMSI number',
        'simlessly_param_ki': 'ki - 32-bit HEX',
        'simlessly_param_opc': 'opc - 32-bit HEX',
        'simlessly_param_configName': 'Configuration Name configured on the platform',
        'simlessly_param_msisdn': 'MSISDN number',
        'simlessly_param_spn': 'If not provided, will use SPN from Configuration',
        'simlessly_param_expireTime': 'Format: yyyy-MM-dd HH:mm:ss (2023-11-21 12:12:22)',
        'simlessly_param_hplmnList': 'HPLMN List, JSON array format, e.g.: ["45400"]',
        'simlessly_param_ehplmnList': 'EHPLMN List, JSON array format, e.g.: ["45400"]',
        'simlessly_param_oplmnList': 'OPLMN List, JSON array format, e.g.: ["45400"]',
        'simlessly_param_fplmnList': 'FPLMN List, JSON array format, e.g.: ["45400"]', 
        'simlessly_param_pin1': 'PIN1',
        'simlessly_param_pin2': 'PIN2',
        'simlessly_param_puk1': 'PUK1', 
        'simlessly_param_puk2': 'PUK2',
        'simlessly_param_multiImsiDataList': 'Multi IMSI Data List',                       
        'simlessly_multi_imsi_title': 'Multi IMSI Data Configuration',
        'simlessly_add_multi_imsi': 'Add Multi IMSI Data',
        'simlessly_remove_multi_imsi': 'Remove',
        'simlessly_imsi': 'IMSI',
        'simlessly_mcc_list': 'MCC List',
        'simlessly_mcc_list_placeholder': 'e.g. ["260", "454"]',
        'simlessly_plmn_list': 'PLMN List',
        'simlessly_hplmn_list': 'HPLMN List',
        'simlessly_fplmn_list': 'FPLMN List',
        'simlessly_ehplmn_list': 'EHPLMN List',
        'simlessly_add_plmn': 'Add PLMN',
        'simlessly_plmn': 'PLMN',
        'simlessly_rat': 'RAT',
        'simlessly_rat_placeholder': 'e.g. 4000 (default)',
        'simlessly_multi_imsi_note': 'Note: MCC List and PLMN related lists need to use JSON array format',
        'simlessly_add_mcc': 'Add MCC',
        'simlessly_multi_imsi_note': 'Note: Both MCC List and PLMN related lists can dynamically add multiple items',                
                
        
        # WorldMove specific
        'worldmove_single_description': 'Select API endpoints and fill in parameters, the system will send single requests and return results.',
        'worldmove_single_note': 'Note: Fixed parameters (merchantId, deptId, token) are automatically included, no need to add manually.',
        'worldmove_batch_description': 'Please upload Excel file, the file format should include the following columns:',
        'worldmove_batch_columns': 'endpoint: API endpoint path (required), imsi: IMSI number or range (e.g., 10001-10050), other required parameter columns',
        'worldmove_batch_note': 'The system will automatically expand IMSI ranges and send separate requests for each IMSI.',
        'worldmove_callback_title': 'Callback Server Information',
        'worldmove_callback_description': 'Callback server is started and listening on the following endpoints:',
        'worldmove_callback_endpoints': '/Api/SOrder/eSIMOrderCallback - eSIM order callback, /Api/SOrder/eSIMOrderandRedeemCallback - eSIM order and redemption callback, /Api/OrderRedemption/RedeemRedemptionCodeCallback - redemption code redemption callback, /Api/SOrder/TopUpCallback - top-up callback',
        'worldmove_callback_logs': 'Callback logs are saved in the CallbackLogs/ directory.',
        'worldmove_ngrok_status': 'Ngrok Tunnel Status',
        'worldmove_recent_callbacks': 'Recent Callback Data',
        'worldmove_callback_files': 'Callback Log Files',
        'worldmove_ngrok_active': 'Ngrok tunnel is active',
        'worldmove_ngrok_inactive': 'Ngrok tunnel is not active',
        'worldmove_public_url': 'Public URL',
        'worldmove_callback_urls': 'Callback URLs',
        'worldmove_provide_urls': 'Please provide these URLs to WorldMove technical support.',
        'worldmove_local_only': 'Callback server can only be accessed locally and cannot receive external callbacks.',
        'worldmove_start_ngrok': 'Start Ngrok Tunnel',
        'worldmove_stop_ngrok': 'Stop Ngrok Tunnel',
        'worldmove_loading_ngrok': 'Loading Ngrok status...',
        'worldmove_starting_ngrok': 'Starting Ngrok tunnel, please wait...',
        'worldmove_stopping_ngrok': 'Stopping Ngrok tunnel, please wait...',
        'worldmove_ngrok_timeout': 'Start timeout',
        'worldmove_ngrok_start_failed': 'Start failed',
        'worldmove_ngrok_stop_failed': 'Stop failed',
        'worldmove_cannot_connect': 'Cannot connect to server',
        'worldmove_no_callback_data': 'No callback data available',
        'worldmove_download_full_log': 'Download Full Log',
        'worldmove_no_callback_files': 'No callback log files',
        'worldmove_cannot_load_callbacks': 'Cannot load recent callback data',
        'worldmove_cannot_load_files': 'Cannot load callback log files',
        'worldmove_modification_time': 'Modification time',
        
        # Dynamic Config
        'worldmove_endpoint_quote_query_all': "Query all quotes",
        'worldmove_endpoint_buy_esim': "Purchase eSIM",
        'worldmove_endpoint_query_esim': "Query eSIM order",
        'worldmove_endpoint_buy_esim_redemption': "Purchase eSIM redemption",
        'worldmove_endpoint_redemption': "Redemption code redemption",
        'worldmove_endpoint_buy_sim': "Purchase SIM card",
        'worldmove_endpoint_deposit': "Deposit/Top-up",
        'worldmove_endpoint_sim_remote_activ': "Remote SIM activation",
        'worldmove_endpoint_sim_traffic_reset': "Reset SIM traffic",
        'worldmove_endpoint_query_usage': "Query usage details",
        'worldmove_endpoint_query_basic_info': "Query basic information",
        'worldmove_endpoint_query_esim_progresses': "Query eSIM progress",
        'worldmove_endpoint_sim_exists': "Check if SIM exists",
        'worldmove_param_merchantId': 'Merchant ID (automatically included)',
        'worldmove_param_token': 'Token (automatically included)',
        'worldmove_param_email': 'User email address',
        'worldmove_param_prodList': 'Product list',
        'worldmove_param_wmproductId': 'Product ID',
        'worldmove_param_qty': 'Quantity',
        'worldmove_param_systemMail': 'System email address (optional)',
        'worldmove_param_orderId': 'Order ID',
        'worldmove_param_qrcodeType': 'QR code type',
        'worldmove_param_rcode': 'Redemption code',
        'worldmove_param_invoiceType': 'Invoice type',
        'worldmove_param_taxId': 'Tax ID',
        'worldmove_param_receivingName': 'Recipient name',
        'worldmove_param_receivingTel': 'Recipient phone number',
        'worldmove_param_receivingAdd': 'Recipient address',
        'worldmove_param_note': 'Note (optional)',
        'worldmove_param_prodList_sim': 'Product list',
        'worldmove_param_productId': 'Product ID',
        'worldmove_param_productName': 'Product name',
        'worldmove_param_prodList_deposit': 'Product list',
        'worldmove_param_day': 'Number of days',
        'worldmove_param_simNum': 'SIM card number',
        'worldmove_param_mcc': 'MCC code',     
        'worldmove_callback_esim_order': 'eSIM order callback',
        'worldmove_callback_esim_order_redeem': 'eSIM order and redemption callback', 
        'worldmove_callback_redemption_code': 'Redemption code redemption callback',
        'worldmove_callback_top_up': 'Top-up callback',
        'worldmove_loading_callbacks': 'Loading recent callback data...',
        'worldmove_loading_files': 'Loading callback log files...',
        'worldmove_ngrok_start_timeout_msg': 'Ngrok tunnel startup is taking too long, please refresh status manually later.'
    },
    
    'zh-CN': {
        'app_name': 'MVNO API整合平台',
        'supplier_api': '供应商API',
        'quadcell': 'Quadcell',
        'montnet': 'MontNet',
        'simlessly': 'Simlessly', 
        'worldmove': 'WorldMove',
        'welcome_message': '欢迎使用MVNO API整合平台',
        'platform_description': '本平台整合了多家SIM卡供应商的API接口，提供统一的界面进行操作。',
        'supported_suppliers': '支持的供应商：',
        'sim_management': '提供SIM卡配置和管理服务',
        'single_request': '单条请求',
        'batch_processing': '批量处理',
        'company_management': '管理公司',
        'select_endpoint': '选择端点',
        'enpoint_info': '端点信息',
        'send_request': '发送请求',
        'response_result': '响应结果',
        'upload_excel': '上传Excel文件',
        'select_Excel_File': '选择Excel文件',        
        'select_company': '选择公司',
        'request_interval': '请求间隔（秒）',
        'request_interval_note': '设置为0表示无间隔，留空默认为0',
        'start_processing': '开始处理',
        'processing': '处理中',
        'add_new_company': '添加新公司',
        'company_name': '公司名称',
        'auth_key': '认证密钥',
        'add': '添加',
        'actions': '操作',
        'edit': '编辑',
        'delete': '删除',
        'no_data': '暂无数据',
        'copyright': 'Quadcell MVNO API集成平台',
        'select_language': '选择语言',
        
        # Common texts
        'please_select': '请选择',
        'loading': '加载中...',
        'success': '成功',
        'error': '错误',
        'download': '下载',
        'refresh': '刷新',
        'stop': '停止',
        'start': '开始',
        'api_Operations': 'API操作',
        'api_endpoint': 'API端点',
        'imsi_number_or_range': "IMSI号码或范围",
        'other_required_parameters': "其他需要的参数",        
        'download_template': '下载Excel模板',
        'template_note': '下载模板文件，按照格式填写数据后再上传',   
        'enter_parameter_value': "请输入参数值",         
        'no_description_available': "无描述信息",
        'request_interval_non_negative': "请求间隔必须为非负数",
        'processing_failed': "处理失败",
        'unknown_error': "未知错误",
        'added_succeed': "添加成功",
        'added_failed': "添加失败",
        'updated_succeed': "更新成功",
        'updated_failed': "更新失败",
        'deleted_succeed': "删除成功",
        'deleted_failed': "删除失败",                                     
        
        # Form labels and buttons
        'single_title': '单条请求说明',
        'batch_title': '批量处理说明',
        'choose_file': '选择文件',
        'no_file_selected': '没有选择文件',
        'excel_files_only': '只支持Excel文件(.xlsx, .xls)',
        'set_to_zero': '设置为0表示无间隔，留空默认为0',
        'click_to_download': '点击下载',
        'process_completed': '处理完成',
        'result_file_generated': '结果文件已生成，',
        'processing_please_wait': '正在处理中，请稍候...',
        'request_processing': '请求处理中，请稍候...',
        'debug_mode': '调试模式',
        'debug_mode_description': '启用后将显示API请求的详细资讯，用于故障排查',
        'debug_information': '调试资讯',
        'api_url': 'API URL',
        'request_json': '请求JSON',
        'encrypted_request': '加密请求',
        'response_raw': '响应',
        'timestamp': '时间戳',
        'formatted_response': '格式化响应', 
        
        # MontNet specific
        'montnet_single_description': '选择API端点和填写参数，系统将发送单条请求并返回结果。',
        'montnet_single_note': '注意：固定参数(authKey)已自动包含，无需手动添加。',
        'montnet_iccid_note': 'ICCID说明：MontNet API要求20位ICCID（包含校验位）。如果您有19位ICCID，可以使用"计算Check Digit"按钮自动计算校验位。',
        'montnet_batch_description': '请上传Excel文件，文件格式应包含以下列：',
        'montnet_batch_columns': 'endpoint: API端点路径, iccid: ICCID号码或范围（如8985211116317800000-8985211116317800999）, 其他需要的参数列',
        'montnet_batch_note': '系统会自动扩展ICCID范围，并为每个ICCID发送单独的请求。',
        'montnet_calculate_check_digit': '计算Check Digit',
        'montnet_endpoint_heartbeat': "检查VMS API服务是否正常",
        'montnet_endpoint_qrysub': "查询用户(SIM卡)的基本信息",
        'montnet_endpoint_qrypacklist': "查询用户已订购套餐的列表",
        'montnet_endpoint_queryQosQuota': "查询用户已订购套餐的用量",
        'montnet_endpoint_addpack': "订阅套餐",
        'montnet_endpoint_delpack': "删除套餐",
        'montnet_endpoint_quota_topup': "增值套餐用量(只适用于'Suspend'套餐)",
        'montnet_endpoint_suspend': "暂停套餐数据服务(只适用于 Vendor = CMHK)",
        'montnet_endpoint_recover': "恢复套餐数据服务",
        'montnet_iccid_must_be_19_digits': "ICCID必须是19位数字",
        'montnet_iccid_19_digits_note': "19位ICCID（不含校验位），必須使用计算功能添加校验位",
        'montnet_iccid_20_digits_note': "20位ICCID（包含校验位），格式正确",
        'montnet_iccid_19_or_20_digits': "ICCID必须是19位（不含校验位）或20位（包含校验位）数字",
        'montnet_enter_valid_19_digits': "请输入有效的19位ICCID（不含校验位）",
        'montnet_check_digit_calculated': "已计算并添加校验位",
        'montnet_iccid_already_20_digits': "ICCID已经是20位（包含校验位），无需重新计算",
        'montnet_no_extra_params': "此端点无需额外参数（固定参数已自动添加）。",
        'montnet_get_params_failed': "获取端点参数失败",
        'montnet_enter_iccid_placeholder': "请输入19位或20位ICCID",     
        
        # Dynamic Config
        'montnet_endpoint_heartbeat': "检查VMS API服务是否正常",
        'montnet_endpoint_qrysub': "查询用户(SIM卡)的基本信息",
        'montnet_endpoint_qrypacklist': "查询用户已订购套餐的列表",
        'montnet_endpoint_queryQosQuota': "查询用户已订购套餐的用量",
        'montnet_endpoint_addpack': "订阅套餐",
        'montnet_endpoint_delpack': "删除套餐",
        'montnet_endpoint_quota_topup': "增值套餐用量(只适用于'Suspend'套餐)",
        'montnet_endpoint_suspend': "暂停套餐数据服务(只适用于 Vendor = CMHK)",
        'montnet_endpoint_recover': "恢复套餐数据服务",
        'montnet_endpoint_qryLocation': "查询现时地址信息",        
        'montnet_param_authKey': '认证密钥 (已自动包含)',
        'montnet_param_imsi': 'IMSI号码 (与iccid/msisdn三选一)',
        'montnet_param_iccid': 'ICCID号码 (与imsi/msisdn三选一)',
        'montnet_param_msisdn': 'MSISDN号码 (与imsi/iccid三选一)',
        'montnet_param_productId': '已订购的套餐ID',
        'montnet_param_subscriptionId': '已订购的套餐订阅ID',
        'montnet_param_packCode': '附加套餐代码',
        'montnet_param_quota': '需要增值的用量(MB)',          
        
        
        # Quadcell specific
        'quadcell_single_description': '选择API端点和填写参数，系统将发送单条请求并返回结果。',
        'quadcell_single_note': '注意：authKey参数默认值为"SYtest21"，但您可以手动修改它。',
        'quadcell_company_select': '选择公司将自动填充authKey，您也可以手动修改',
        'quadcell_batch_description': '请上传Excel文件，文件格式应包含以下列：',
        'quadcell_batch_columns': 'endpoint: API端点路径, imsi: IMSI号码或范围（如454070041610000-454070041610999）- 同样适用于ICCID/MSISDN, 其他需要的参数列',
        'quadcell_batch_note': '系统会自动扩展IMSI/ICCID/MSISDN范围，并为每个SIM发送单独的请求。',
        'quadcell_company_manager': '管理公司',        
        'quadcell_company_mapping': '公司映射管理',
        'quadcell_company_description': '在这里您可以添加、编辑和删除公司名称与authKey的映射关系。',
        'quadcell_company_usage': '在单条请求和批量处理中，您可以选择公司名称来自动填充authKey。',
        'quadcell_company_authkey_priority': '选择公司将使用该公司的authKey，优先级高于Excel中的authKey',
        'quadcell_company_select': '请选择公司',
        'quadcell_fillin_company': '请填写公司名称和AuthKey',
        'quadcell_input_new_authkey': '请输入新的AuthKey - ',
        'quadcell_blank_authkey_note': 'AuthKey不能为空',
        'quadcell_delete_company_note': '请再次确认是要删除 - ',                
        
        # Dynamic Config  
        'quadcell_endpoint_qrysub': "查询用户基本信息",
        'quadcell_endpoint_qryusage': "查询用户数据使用量",
        'quadcell_endpoint_qrypacklist': "查询用户已订购套餐列表",
        'quadcell_endpoint_qrypackquota': "查询用户套餐用量",
        'quadcell_endpoint_qryquota': "查询用户FUP套餐用量",
        'quadcell_endpoint_addsub': "创建用户订阅",
        'quadcell_endpoint_delsub': "删除用户订阅",
        'quadcell_endpoint_suspend': "暂停用户服务",
        'quadcell_endpoint_recover': "恢复用户服务",
        'quadcell_endpoint_extend': "延长用户服务有效期",
        'quadcell_endpoint_addpack': "添加服务套餐",
        'quadcell_endpoint_delpack': "删除服务套餐",
        'quadcell_endpoint_rechargepackquota': "为套餐用量充值",
        'quadcell_endpoint_resetquota': "重置FUP数据用量",
        'quadcell_endpoint_clearquota': "清空FUP剩余用量",
        'quadcell_endpoint_rechargequota': "充值FUP剩余用量",
        'quadcell_endpoint_addFupCode': "为数据套餐添加FUP规则（仅45400/45431）",
        'quadcell_endpoint_delFupCode': "删除数据套餐的FUP规则（仅45400/45431）",
        'quadcell_endpoint_cancelLoc': "强制用户从网络分离",
        'quadcell_endpoint_submitsms': "向用户发送短信",
        'quadcell_endpoint_qrystatus': "查询eSIM状态",
        'quadcell_endpoint_esim_order': "订购eSIM并添加套餐",
        'quadcell_endpoint_esim_qryaccount': "查询用户账号的eSIM池",
        'quadcell_endpoint_qryorderhistory': "查询订购套餐历史记录",
        'quadcell_param_imsi': 'IMSI号码（与iccid/msisdn三选一）',
        'quadcell_param_iccid': 'ICCID号码（与imsi/msisdn三选一）',
        'quadcell_param_msisdn': 'MSISDN号码（与imsi/iccid三选一）',
        'quadcell_param_beginDate': '开始日期（yyyymmdd）',
        'quadcell_param_endDate': '结束日期（yyyymmdd）',
        'quadcell_param_packCode': '套餐代码',
        'quadcell_param_planCode': '服务套餐代码',
        'quadcell_param_validity': '有效期（天数）',
        'quadcell_param_lastActiveTime': '最后激活时间（yyyymm）',
        'quadcell_param_initBalance': '初始余额',
        'quadcell_param_serviceId': '服务ID（默认00表示所有服务）',
        'quadcell_param_append': '延展方式：0=重置，1=追加',
        'quadcell_param_noOfDays': '延展天数（1-99999）',
        'quadcell_param_activeType': '激活类型：0=按日期，1=按国家',
        'quadcell_param_activeDate': '激活日期（yyyymmdd）',
        'quadcell_param_expTime': '删除时间（yyyymmddhhmmss）',
        'quadcell_param_packOrderSn': '套餐订单序列号',
        'quadcell_param_rechargeQuota': '充值用量（MB/分钟/条）',
        'quadcell_param_rechargeValue': '充值数据量（MB）',
        'quadcell_param_fupCode': 'FUP规则代码',
        'quadcell_param_smsMt': '接收方MSISDN',
        'quadcell_param_smsMo': '发送方MSISDN（由Quadcell指定）',
        'quadcell_param_smsText': '短信内容',
        'quadcell_param_account': '客户账号名',
        'quadcell_param_imsiType': '支持45407/45400/45412',
        'quadcell_param_page': '页面（默认第一版）',
        'quadcell_param_pageSize': '页面数量（默认20页）',              
        
        
        # Simlessly specific
        'simlessly_single_description': '选择API端点和填写参数，系统将发送单条请求并返回结果。',
        'simlessly_batch_description': '请上传Excel文件，文件格式应包含以下列：',
        'simlessly_batch_columns': 'endpoint: API端点路径, iccid: ICCID号码或范围（如8985211116317800000-8985211116317800999）, 其他需要的参数列',
        'simlessly_batch_note': '系统会自动扩展ICCID范围，并为每个ICCID发送单独的请求。',
        'simlessly_dot_notation': '注意：使用点号表示法创建嵌套结构（例如：\'pageParam.pageNum\'）',
        'simlessly_no_extra_params': '此端点无需额外参数。',
        'simlessly_get_params_failed': '获取端点参数失败',
        'simlessly_list_param_note': '（使用JSON数组格式，例如：["45400", "45407"]）',
        'simlessly_list_param_example': '例如：["45400", "45407"]',
        
        # Dynamic Config        
        'simlessly_endpoint_profile_detail': "查询eSIM详细信息",
        'simlessly_endpoint_profile_log': "查询eSIM历史记录", 
        'simlessly_endpoint_profile_delete': "删除eSIM配置",
        'simlessly_endpoint_profile_updateParam': "更新eSIM配置",          
        'simlessly_endpoint_ac_generate': "生成eSIM",
        'simlessly_param_iccid': 'ICCID号码',
        'simlessly_param_pageParam_pageNum': '页码',
        'simlessly_param_pageParam_pageSize': '每页大小',
        'simlessly_param_imsi': 'IMSI号码',
        'simlessly_param_ki': 'ki - 32位HEX',
        'simlessly_param_opc': 'opc - 32位HEX',
        'simlessly_param_configName': '平台配置好的Configuration Name',
        'simlessly_param_msisdn': 'MSISDN号码',
        'simlessly_param_spn': '如果不提供，会使用Configuration中的SPN',
        'simlessly_param_expireTime': '格式: yyyy-MM-dd HH:mm:ss (2023-11-21 12:12:22)',
        'simlessly_param_hplmnList': 'HPLMN列表, JSON数组格式, 例如: ["45400"]',
        'simlessly_param_ehplmnList': 'EHPLMN列表, JSON数组格式, 例如: ["45400"]',
        'simlessly_param_oplmnList': 'OPLMN列表, JSON数组格式, 例如: ["45400"]',
        'simlessly_param_fplmnList': 'FPLMN列表, JSON数组格式, 例如: ["45400"]',        
        
        # WorldMove specific
        'worldmove_single_description': '选择API端点和填写参数，系统将发送单条请求并返回结果。',
        'worldmove_single_note': '注意：固定参数（merchantId, deptId, token）已自动包含，无需手动添加。',
        'worldmove_batch_description': '请上传Excel文件，文件格式应包含以下列：',
        'worldmove_batch_columns': 'endpoint: API端点路径（必须）, imsi: IMSI号码或范围（如10001-10050）, 其他需要的参数列',
        'worldmove_batch_note': '系统会自动扩展IMSI范围，并为每个IMSI发送单独的请求。',
        'worldmove_callback_title': '回调服务器信息',
        'worldmove_callback_description': '回调服务器已启动并监听以下端点：',
        'worldmove_callback_endpoints': '/Api/SOrder/eSIMOrderCallback - eSIM订单回调, /Api/SOrder/eSIMOrderandRedeemCallback - eSIM订单和兑换回调, /Api/OrderRedemption/RedeemRedemptionCodeCallback - 兑换码兑换回调, /Api/SOrder/TopUpCallback - 充值回调',
        'worldmove_callback_logs': '回调日志保存在 CallbackLogs/ 目录中。',
        'worldmove_ngrok_status': 'Ngrok隧道状态',
        'worldmove_recent_callbacks': '最近回调数据',
        'worldmove_callback_files': '回调日志文件',
        'worldmove_ngrok_active': 'Ngrok隧道已启动',
        'worldmove_ngrok_inactive': 'Ngrok隧道未启动',
        'worldmove_public_url': '公网URL',
        'worldmove_callback_urls': '回调URL',
        'worldmove_provide_urls': '请将这些URL提供给WorldMove技术支持。',
        'worldmove_local_only': '回调服务器只能在本地访问，无法接收外部回调。',
        'worldmove_start_ngrok': '启动Ngrok隧道',
        'worldmove_stop_ngrok': '停止Ngrok隧道',
        'worldmove_loading_ngrok': '正在加载Ngrok状态...',
        'worldmove_starting_ngrok': '正在启动Ngrok隧道，请稍候...',
        'worldmove_stopping_ngrok': '正在停止Ngrok隧道，请稍候...',
        'worldmove_ngrok_timeout': '启动超时',
        'worldmove_ngrok_start_failed': '启动失败',
        'worldmove_ngrok_stop_failed': '停止失败',
        'worldmove_cannot_connect': '无法连接到服务器',
        'worldmove_no_callback_data': '暂无回调数据',
        'worldmove_download_full_log': '下载完整日志',
        'worldmove_no_callback_files': '暂无回调日志文件',
        'worldmove_cannot_load_callbacks': '无法加载最近回调数据',
        'worldmove_cannot_load_files': '无法加载回调日志文件',
        'worldmove_modification_time': '修改时间',
        
        # Dynamic Config
        'worldmove_endpoint_quote_query_all': "查询所有报价",
        'worldmove_endpoint_buy_esim': "购买eSIM",
        'worldmove_endpoint_query_esim': "查询eSIM订单",
        'worldmove_endpoint_buy_esim_redemption': "购买eSIM兑换",
        'worldmove_endpoint_redemption': "兑换码兑换",
        'worldmove_endpoint_buy_sim': "购买SIM卡",
        'worldmove_endpoint_deposit': "存款/充值",
        'worldmove_endpoint_sim_remote_activ': "远程激活SIM卡",
        'worldmove_endpoint_sim_traffic_reset': "重置SIM卡流量",
        'worldmove_endpoint_query_usage': "查询使用详情",
        'worldmove_endpoint_query_basic_info': "查询基本信息",
        'worldmove_endpoint_query_esim_progresses': "查询eSIM进度",
        'worldmove_endpoint_sim_exists': "检查SIM卡是否存在",
        'worldmove_param_merchantId': '商户ID（已自动包含）',
        'worldmove_param_token': '令牌（已自动包含）',
        'worldmove_param_email': '用户邮箱地址',
        'worldmove_param_prodList': '产品列表',
        'worldmove_param_wmproductId': '产品ID',
        'worldmove_param_qty': '数量',
        'worldmove_param_systemMail': '系统邮件地址（可选）',
        'worldmove_param_orderId': '订单ID',
        'worldmove_param_qrcodeType': '二维码类型',
        'worldmove_param_rcode': '兑换码',
        'worldmove_param_invoiceType': '发票类型',
        'worldmove_param_taxId': '税号',
        'worldmove_param_receivingName': '收件人姓名',
        'worldmove_param_receivingTel': '收件人电话',
        'worldmove_param_receivingAdd': '收件地址',
        'worldmove_param_note': '备注（可选）',
        'worldmove_param_prodList_sim': '产品列表',
        'worldmove_param_productId': '产品ID',
        'worldmove_param_productName': '产品名称',
        'worldmove_param_prodList_deposit': '产品列表',
        'worldmove_param_day': '天数',
        'worldmove_param_simNum': 'SIM卡号',
        'worldmove_param_mcc': 'MCC代码',    
        'worldmove_callback_esim_order': 'eSIM订单回调',
        'worldmove_callback_esim_order_redeem': 'eSIM订单和兑换回调',
        'worldmove_callback_redemption_code': '兑换码兑换回调', 
        'worldmove_callback_top_up': '充值回调',
        'worldmove_loading_callbacks': '正在加载最近回调数据...',
        'worldmove_loading_files': '正在加载回调日志文件...',
        'worldmove_ngrok_start_timeout_msg': 'Ngrok隧道启动时间过长，请稍后手动刷新状态。'                  
    },
    
    'zh-TW': {
        'app_name': 'MVNO API整合平台',
        'supplier_api': '供應商API',
        'quadcell': 'Quadcell',
        'montnet': 'MontNet',
        'simlessly': 'Simlessly',
        'worldmove': 'WorldMove',
        'welcome_message': '歡迎使用MVNO API整合平台',
        'platform_description': '本平台整合了多家SIM卡供應商的API接口，提供統一的界面進行操作。',
        'supported_suppliers': '支援的供應商：',
        'sim_management': '提供SIM卡配置和管理服務',
        'single_request': '單條請求',
        'batch_processing': '批次處理',
        'company_management': '管理公司',
        'select_endpoint': '選擇端點',
        'enpoint_info': '端點信息',
        'send_request': '發送請求',
        'response_result': '響應結果',
        'upload_excel': '上傳Excel檔案',
        'select_Excel_File': '選擇Excel文件',        
        'select_company': '選擇公司',
        'request_interval': '請求間隔（秒）',
        'request_interval_note': '設置為0表示無間隔，留空默認為0',
        'start_processing': '開始處理',
        'processing': '處理中',
        'add_new_company': '新增公司',
        'company_name': '公司名稱',
        'auth_key': '認證密鑰',
        'add': '新增',
        'actions': '操作',
        'edit': '編輯',
        'delete': '刪除',
        'no_data': '暫無資料',
        'copyright': 'Quadcell MVNO API整合平台',
        'select_language': '選擇語言',
        
        # Common texts
        'please_select': '請選擇',
        'loading': '加載中...',
        'success': '成功',
        'error': '錯誤',
        'download': '下載',
        'refresh': '刷新',
        'stop': '停止',
        'start': '開始',
        'api_Operations': 'API操作',
        'api_endpoint': 'API端點',
        'imsi_number_or_range': "IMSI號碼或範圍",
        'other_required_parameters': "其他需要的參數",
        'download_template': '下載Excel模板',
        'template_note': '下載模板檔案，按照格式填寫數據後再上傳',   
        'enter_parameter_value': "請輸入參數值",
        'no_description_available': "無描述信息",
        'request_interval_non_negative': "請求間隔必須為非負數",
        'processing_failed': "處理失敗",
        'unknown_error': "未知錯誤",    
        'added_succeed': "添加成功",
        'added_failed': "添加失敗",
        'updated_succeed': "更新成功",
        'updated_failed': "更新失敗",
        'deleted_succeed': "刪除成功",
        'deleted_failed': "刪除失敗",                                            
        
        # Form labels and buttons
        'single_title': '單條請求説明',
        'batch_title': '批量處理説明',        
        'choose_file': '選擇檔案',
        'no_file_selected': '沒有選擇檔案',
        'excel_files_only': '只支援Excel檔案(.xlsx, .xls)',
        'set_to_zero': '設置為0表示無間隔，留空預設為0',
        'click_to_download': '點擊下載',
        'process_completed': '處理完成',
        'result_file_generated': '結果檔案已生成，',
        'processing_please_wait': '正在處理中，請稍候...',
        'request_processing': '請求處理中，請稍候...',
        'debug_mode': '調試模式',
        'debug_mode_description': '啟用後將顯示API請求的詳細資訊，用於故障排查',
        'debug_information': '調試資訊',
        'api_url': 'API URL',
        'request_json': '請求JSON',
        'encrypted_request': '加密請求',
        'response_raw': '響應',
        'timestamp': '時間戳',
        'formatted_response': '格式化響應',                
        
        # MontNet specific
        'montnet_single_description': '選擇API端點和填寫參數，系統將發送單條請求並返回結果。',
        'montnet_single_note': '注意：固定參數(authKey)已自動包含，無需手動添加。',
        'montnet_iccid_note': 'ICCID說明：MontNet API要求20位ICCID（包含校驗位）。如果您有19位ICCID，可以使用"計算Check Digit"按鈕自動計算校驗位。',
        'montnet_batch_description': '請上傳Excel檔案，檔案格式應包含以下列：',
        'montnet_batch_columns': 'endpoint: API端點路徑, iccid: ICCID號碼或範圍（如8985211116317800000-8985211116317800999）, 其他需要的參數列',
        'montnet_batch_note': '系統會自動擴展ICCID範圍，並為每個ICCID發送單獨的請求。',
        'montnet_calculate_check_digit': '計算Check Digit',
        'montnet_endpoint_heartbeat': "檢查VMS API服務是否正常",
        'montnet_endpoint_qrysub': "查詢用戶(SIM卡)的基本信息",
        'montnet_endpoint_qrypacklist': "查詢用戶已訂購套餐的列表",
        'montnet_endpoint_queryQosQuota': "查詢用戶已訂購套餐的用量",
        'montnet_endpoint_addpack': "訂閱套餐",
        'montnet_endpoint_delpack': "刪除套餐",
        'montnet_endpoint_quota_topup': "增值套餐用量(只適用於'Suspend'套餐)",
        'montnet_endpoint_suspend': "暫停套餐數據服務(只適用於 Vendor = CMHK)",
        'montnet_endpoint_recover': "恢復套餐數據服務",
        'montnet_iccid_must_be_19_digits': "ICCID必須是19位數字",
        'montnet_iccid_19_digits_note': "19位ICCID（不含校驗位），必須使用計算功能添加校驗位",
        'montnet_iccid_20_digits_note': "20位ICCID（包含校驗位），格式正確",
        'montnet_iccid_19_or_20_digits': "ICCID必須是19位（不含校驗位）或20位（包含校驗位）數字",
        'montnet_enter_valid_19_digits': "請輸入有效的19位ICCID（不含校驗位）",
        'montnet_check_digit_calculated': "已計算並添加校驗位",
        'montnet_iccid_already_20_digits': "ICCID已經是20位（包含校驗位），無需重新計算",
        'montnet_no_extra_params': "此端點無需額外參數（固定參數已自動添加）。",
        'montnet_get_params_failed': "獲取端點參數失敗",
        'montnet_enter_iccid_placeholder': "請輸入19位或20位ICCID",
        
        # Dynamic Config
        'montnet_endpoint_heartbeat': "檢查VMS API服務是否正常",
        'montnet_endpoint_qrysub': "查詢用戶(SIM卡)的基本信息",
        'montnet_endpoint_qrypacklist': "查詢用戶已訂購套餐的列表",
        'montnet_endpoint_queryQosQuota': "查詢用戶已訂購套餐的用量",
        'montnet_endpoint_addpack': "訂閱套餐",
        'montnet_endpoint_delpack': "刪除套餐",
        'montnet_endpoint_quota_topup': "增值套餐用量(只適用於'Suspend'套餐)",
        'montnet_endpoint_suspend': "暫停套餐數據服務(只適用於 Vendor = CMHK)",
        'montnet_endpoint_recover': "恢復套餐數據服務",
        'montnet_endpoint_qryLocation': "查詢現時地址信息",        
        'montnet_param_authKey': '認證密鑰 (已自動包含)',
        'montnet_param_imsi': 'IMSI號碼 (與iccid/msisdn三選一)',
        'montnet_param_iccid': 'ICCID號碼 (與imsi/msisdn三選一)',
        'montnet_param_msisdn': 'MSISDN號碼 (與imsi/iccid三選一)',
        'montnet_param_productId': '已訂購的套餐ID',
        'montnet_param_subscriptionId': '已訂購的套餐訂閱ID',
        'montnet_param_packCode': '附加套餐代碼',
        'montnet_param_quota': '需要增值的用量(MB)',                
        
        
        # Quadcell specific
        'quadcell_single_description': '選擇API端點和填寫參數，系統將發送單條請求並返回結果。',
        'quadcell_single_note': '注意：authKey參數預設值為"SYtest21"，但您可以手動修改它。',
        'quadcell_company_select': '選擇公司將自動填充authKey，您也可以手動修改',
        'quadcell_batch_description': '請上傳Excel檔案，檔案格式應包含以下列：',
        'quadcell_batch_columns': 'endpoint: API端點路徑, imsi: IMSI號碼或範圍（如454070041610000-454070041610999）- 同樣適用於ICCID/MSISDN, 其他需要的參數列',
        'quadcell_batch_note': '系統會自動擴展IMSI/ICCID/MSISDN範圍，並為每個SIM發送單獨的請求。',
        'quadcell_company_manager': '管理公司',
        'quadcell_company_mapping': '公司映射管理',
        'quadcell_company_description': '在這裡您可以新增、編輯和刪除公司名稱與authKey的映射關係。',
        'quadcell_company_usage': '在單條請求和批次處理中，您可以選擇公司名稱來自動填充authKey。',
        'quadcell_company_authkey_priority': '選擇公司將使用該公司的authKey，優先級高於Excel中的authKey',
        'quadcell_company_select': '請選擇公司',
        'quadcell_fillin_company': '請填寫公司名稱和AuthKey', 
        'quadcell_input_new_authkey': '請輸入新的AuthKey - ',
        'quadcell_blank_authkey_note': 'AuthKey不能爲空',
        'quadcell_delete_company_note': '請再次確認是要刪除 - ',                                       
        
        # Dynamic Config
        'quadcell_endpoint_qrysub': "查詢用戶基本信息",
        'quadcell_endpoint_qryusage': "查詢用戶數據使用量",
        'quadcell_endpoint_qrypacklist': "查詢用戶已訂購套餐列表",
        'quadcell_endpoint_qrypackquota': "查詢用戶套餐用量",
        'quadcell_endpoint_qryquota': "查詢用戶FUP套餐用量",
        'quadcell_endpoint_addsub': "創建用戶訂閱",
        'quadcell_endpoint_delsub': "刪除用戶訂閱",
        'quadcell_endpoint_suspend': "暫停用戶服務",
        'quadcell_endpoint_recover': "恢復用戶服務",
        'quadcell_endpoint_extend': "延長用戶服務有效期",
        'quadcell_endpoint_addpack': "添加服務套餐",
        'quadcell_endpoint_delpack': "刪除服務套餐",
        'quadcell_endpoint_rechargepackquota': "為套餐用量充值",
        'quadcell_endpoint_resetquota': "重置FUP數據用量",
        'quadcell_endpoint_clearquota': "清空FUP剩餘用量",
        'quadcell_endpoint_rechargequota': "充值FUP剩餘用量",
        'quadcell_endpoint_addFupCode': "為數據套餐添加FUP規則（僅45400/45431）",
        'quadcell_endpoint_delFupCode': "刪除數據套餐的FUP規則（僅45400/45431）",
        'quadcell_endpoint_cancelLoc': "強制用戶從網絡分離",
        'quadcell_endpoint_submitsms': "向用戶發送短信",
        'quadcell_endpoint_qrystatus': "查詢eSIM狀態",
        'quadcell_endpoint_esim_order': "訂購eSIM並添加套餐",
        'quadcell_endpoint_esim_qryaccount': "查詢用戶賬號的eSIM池",
        'quadcell_endpoint_qryorderhistory': "查詢訂購套餐歷史記錄",
        'quadcell_param_imsi': 'IMSI號碼（與iccid/msisdn三選一）',
        'quadcell_param_iccid': 'ICCID號碼（與imsi/msisdn三選一）',
        'quadcell_param_msisdn': 'MSISDN號碼（與imsi/iccid三選一）',
        'quadcell_param_beginDate': '開始日期（yyyymmdd）',
        'quadcell_param_endDate': '結束日期（yyyymmdd）',
        'quadcell_param_packCode': '套餐代碼',
        'quadcell_param_planCode': '服務套餐代碼',
        'quadcell_param_validity': '有效期（天數）',
        'quadcell_param_lastActiveTime': '最後激活時間（yyyymm）',
        'quadcell_param_initBalance': '初始餘額',
        'quadcell_param_serviceId': '服務ID（默認00表示所有服務）',
        'quadcell_param_append': '延展方式：0=重置，1=追加',
        'quadcell_param_noOfDays': '延展天數（1-99999）',
        'quadcell_param_activeType': '激活類型：0=按日期，1=按國家',
        'quadcell_param_activeDate': '激活日期（yyyymmdd）',
        'quadcell_param_expTime': '刪除時間（yyyymmddhhmmss）',
        'quadcell_param_packOrderSn': '套餐訂單序列號',
        'quadcell_param_rechargeQuota': '充值用量（MB/分鐘/條）',
        'quadcell_param_rechargeValue': '充值數據量（MB）',
        'quadcell_param_fupCode': 'FUP規則代碼',
        'quadcell_param_smsMt': '接收方MSISDN',
        'quadcell_param_smsMo': '發送方MSISDN（由Quadcell指定）',
        'quadcell_param_smsText': '短信內容',
        'quadcell_param_account': '客戶賬號名',
        'quadcell_param_imsiType': '支持45407/45400/45412',
        'quadcell_param_page': '頁面（默認第一版）',
        'quadcell_param_pageSize': '頁面數量（默認20頁）',
                        
        
        # Simlessly specific
        'simlessly_single_description': '選擇API端點和填寫參數，系統將發送單條請求並返回結果。',
        'simlessly_batch_description': '請上傳Excel檔案，檔案格式應包含以下列：',
        'simlessly_batch_columns': 'endpoint: API端點路徑, iccid: ICCID號碼或範圍（如8985211116317800000-8985211116317800999）, 其他需要的參數列',
        'simlessly_batch_note': '系統會自動擴展ICCID範圍，並為每個ICCID發送單獨的請求。',
        'simlessly_dot_notation': '注意：使用點號表示法創建嵌套結構（例如：\'pageParam.pageNum\'）',
        'simlessly_no_extra_params': '此端點無需額外參數。',
        'simlessly_get_params_failed': '獲取端點參數失敗',
        'simlessly_list_param_note': '（使用JSON數組格式，例如：["45400", "45407"]）',
        'simlessly_list_param_example': '例如：["45400", "45407"]',
        
        # Dynamic Config        
        'simlessly_endpoint_profile_detail': "查詢eSIM詳細信息",
        'simlessly_endpoint_profile_log': "查詢eSIM歷史記錄", 
        'simlessly_endpoint_profile_delete': "刪除eSIM配置",
        'simlessly_endpoint_profile_updateParam': "更新eSIM配置",         
        'simlessly_endpoint_ac_generate': "生成eSIM",
        'simlessly_param_iccid': 'ICCID號碼',
        'simlessly_param_pageParam_pageNum': '頁碼',
        'simlessly_param_pageParam_pageSize': '每頁大小',
        'simlessly_param_imsi': 'IMSI號碼',
        'simlessly_param_ki': 'ki - 32位HEX',
        'simlessly_param_opc': 'opc - 32位HEX',
        'simlessly_param_configName': '平台配置好的Configuration Name',
        'simlessly_param_msisdn': 'MSISDN號碼',
        'simlessly_param_spn': '如果不提供，會使用Configuration中的SPN',
        'simlessly_param_expireTime': '格式: yyyy-MM-dd HH:mm:ss (2023-11-21 12:12:22)',
        'simlessly_param_hplmnList': 'HPLMN列表, JSON數組格式, 例如: ["45400"]',
        'simlessly_param_ehplmnList': 'EHPLMN列表, JSON數組格式, 例如: ["45400"]',
        'simlessly_param_oplmnList': 'OPLMN列表, JSON數組格式, 例如: ["45400"]',
        'simlessly_param_fplmnList': 'FPLMN列表, JSON數組格式, 例如: ["45400"]',
        'simlessly_param_pin1': 'PIN1',
        'simlessly_param_pin2': 'PIN2', 
        'simlessly_param_puk1': 'PUK1',
        'simlessly_param_puk2': 'PUK2',
        'simlessly_param_multiImsiDataList': 'Multi IMSI數據列表',
        'simlessly_multi_imsi_title': 'Multi IMSI數據配置',
        'simlessly_add_multi_imsi': '添加Multi IMSI數據',
        'simlessly_remove_multi_imsi': '移除',
        'simlessly_imsi': 'IMSI',
        'simlessly_mcc_list': 'MCC列表',
        'simlessly_mcc_list_placeholder': '例如: ["260", "454"]',
        'simlessly_plmn_list': 'PLMN列表',
        'simlessly_hplmn_list': 'HPLMN列表', 
        'simlessly_fplmn_list': 'FPLMN列表',
        'simlessly_ehplmn_list': 'EHPLMN列表',
        'simlessly_add_plmn': '添加PLMN',
        'simlessly_plmn': 'PLMN',
        'simlessly_rat': 'RAT',
        'simlessly_rat_placeholder': '例如: 4000 (默認值)',
        'simlessly_multi_imsi_note': '注意：MCC列表和PLMN相關列表都需要使用JSON數組格式',
        'simlessly_add_mcc': '添加MCC',
        'simlessly_multi_imsi_note': '注意：MCC列表和PLMN相關列表都可以動態添加多個項目',                
                
        
        # WorldMove specific
        'worldmove_single_description': '選擇API端點和填寫參數，系統將發送單條請求並返回結果。',
        'worldmove_single_note': '注意：固定參數（merchantId, deptId, token）已自動包含，無需手動添加。',
        'worldmove_batch_description': '請上傳Excel檔案，檔案格式應包含以下列：',
        'worldmove_batch_columns': 'endpoint: API端點路徑（必須）, imsi: IMSI號碼或範圍（如10001-10050）, 其他需要的參數列',
        'worldmove_batch_note': '系統會自動擴展IMSI範圍，並為每個IMSI發送單獨的請求。',
        'worldmove_callback_title': '回調伺服器信息',
        'worldmove_callback_description': '回調伺服器已啟動並監聽以下端點：',
        'worldmove_callback_endpoints': '/Api/SOrder/eSIMOrderCallback - eSIM訂單回調, /Api/SOrder/eSIMOrderandRedeemCallback - eSIM訂單和兌換回調, /Api/OrderRedemption/RedeemRedemptionCodeCallback - 兌換碼兌換回調, /Api/SOrder/TopUpCallback - 充值回調',
        'worldmove_callback_logs': '回調日誌保存在 CallbackLogs/ 目錄中。',
        'worldmove_ngrok_status': 'Ngrok隧道狀態',
        'worldmove_recent_callbacks': '最近回調數據',
        'worldmove_callback_files': '回調日誌檔案',
        'worldmove_ngrok_active': 'Ngrok隧道已啟動',
        'worldmove_ngrok_inactive': 'Ngrok隧道未啟動',
        'worldmove_public_url': '公網URL',
        'worldmove_callback_urls': '回調URL',
        'worldmove_provide_urls': '請將這些URL提供給WorldMove技術支援。',
        'worldmove_local_only': '回調伺服器只能在本地訪問，無法接收外部回調。',
        'worldmove_start_ngrok': '啟動Ngrok隧道',
        'worldmove_stop_ngrok': '停止Ngrok隧道',
        'worldmove_loading_ngrok': '正在加載Ngrok狀態...',
        'worldmove_starting_ngrok': '正在啟動Ngrok隧道，請稍候...',
        'worldmove_stopping_ngrok': '正在停止Ngrok隧道，請稍候...',
        'worldmove_ngrok_timeout': '啟動超時',
        'worldmove_ngrok_start_failed': '啟動失敗',
        'worldmove_ngrok_stop_failed': '停止失敗',
        'worldmove_cannot_connect': '無法連接到伺服器',
        'worldmove_no_callback_data': '暫無回調數據',
        'worldmove_download_full_log': '下載完整日誌',
        'worldmove_no_callback_files': '暫無回調日誌檔案',
        'worldmove_cannot_load_callbacks': '無法加載最近回調數據',
        'worldmove_cannot_load_files': '無法加載回調日誌檔案',
        'worldmove_modification_time': '修改時間',
        
        # Dynamic Config
        'worldmove_endpoint_quote_query_all': "查詢所有報價",
        'worldmove_endpoint_buy_esim': "購買eSIM",
        'worldmove_endpoint_query_esim': "查詢eSIM訂單",
        'worldmove_endpoint_buy_esim_redemption': "購買eSIM兌換",
        'worldmove_endpoint_redemption': "兌換碼兌換",
        'worldmove_endpoint_buy_sim': "購買SIM卡",
        'worldmove_endpoint_deposit': "存款/充值",
        'worldmove_endpoint_sim_remote_activ': "遠程激活SIM卡",
        'worldmove_endpoint_sim_traffic_reset': "重置SIM卡流量",
        'worldmove_endpoint_query_usage': "查詢使用詳情",
        'worldmove_endpoint_query_basic_info': "查詢基本信息",
        'worldmove_endpoint_query_esim_progresses': "查詢eSIM進度",
        'worldmove_endpoint_sim_exists': "檢查SIM卡是否存在",
        'worldmove_param_merchantId': '商戶ID（已自動包含）',
        'worldmove_param_token': '令牌（已自動包含）',
        'worldmove_param_email': '用戶郵箱地址',
        'worldmove_param_prodList': '產品列表',
        'worldmove_param_wmproductId': '產品ID',
        'worldmove_param_qty': '數量',
        'worldmove_param_systemMail': '系統郵件地址（可選）',
        'worldmove_param_orderId': '訂單ID',
        'worldmove_param_qrcodeType': '二維碼類型',
        'worldmove_param_rcode': '兌換碼',
        'worldmove_param_invoiceType': '發票類型',
        'worldmove_param_taxId': '稅號',
        'worldmove_param_receivingName': '收件人姓名',
        'worldmove_param_receivingTel': '收件人電話',
        'worldmove_param_receivingAdd': '收件地址',
        'worldmove_param_note': '備註（可選）',
        'worldmove_param_prodList_sim': '產品列表',
        'worldmove_param_productId': '產品ID',
        'worldmove_param_productName': '產品名稱',
        'worldmove_param_prodList_deposit': '產品列表',
        'worldmove_param_day': '天數',
        'worldmove_param_simNum': 'SIM卡號',
        'worldmove_param_mcc': 'MCC代碼',
        'worldmove_callback_esim_order': 'eSIM訂單回調',
        'worldmove_callback_esim_order_redeem': 'eSIM訂單和兌換回調',
        'worldmove_callback_redemption_code': '兌換碼兌換回調',
        'worldmove_callback_top_up': '充值回調',
        'worldmove_loading_callbacks': '正在加載最近回調數據...',
        'worldmove_loading_files': '正在加載回調日誌檔案...',
        'worldmove_ngrok_start_timeout_msg': 'Ngrok隧道啟動時間過長，請稍後手動刷新狀態。',
        
        #Sim Resource
        'sim_resource_management': 'SIM 資源管理',
        'sim_resource_description': '集中管理實體卡、eSIM、SoftProfile，所有欄位完全自訂',
        'support_physical_esim_softprofile': '支援實體卡 · eSIM · SoftProfile · 任意自訂欄位',
        'search_type': '搜索類型',
        'all_suppliers': '所有供應商',
        'add_resource': '添加資源',
        'export_csv': '導出 CSV',
        'type': '類型',
        'supplier': '供應商',
        'attributes': '屬性',
        'created_at': '創建時間',
        'actions': '操作',
        'edit': '編輯',
        'delete': '刪除',
        'physical_card': '實體卡',
        'soft_profile': 'SoftProfile',
        'esim': 'eSIM',
        'add_field': '添加字段',
        'save': '保存',
        'confirm_delete': '確認刪除？',
        'sim_resources': 'SIM 資源',
        'my_sim_inventory': '我的 SIM 卡庫存',
        'current_inventory': '目前庫存',
        'total': '總庫存',
        'cards': '張',
        'other_types': '其他類型',
        'inventory_by_supplier': '依供應商庫存分布',
        'import_resources': '導入資源',
        'import_tip': '請使用下載的範本填寫，支援 CSV 或 Excel 格式',
        'import_failed': '導入失敗',
        'search_provider': '搜索 Provider',
        'search_card_type': '搜索 CardType',
        'search_resources_type': '搜索 ResourcesType',
        'search_batch': '搜索 Batch',
        'search_received_date': '搜索 ReceivedDate',
        'search_imsi': '搜索 IMSI',
        'search_iccid': '搜索 ICCID',
        'search_msisdn': '搜索 MSISDN'
        
    }
}